public class Ex1{
public static void main (String[] args){

try{
int vetor[] = new int[4];

System.out.println("Antes da exception");

vetor[4] = 1;

}
catch(ArrayIndexOutOfBoundsException exception){
System.out.printl("Exceção ao acessar um indice do vetor não existente");
}

System.out.println("A impressão desse texto não ocorrera após a exception");

}
}
